services:
  web:
    build: ./backend
    ports:
      - "8080:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/tasks

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tasks"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:8080
    ports:
      - "3000:80"
    depends_on:
      - web
